# Generated by Django 5.1.1 on 2024-10-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0002_alter_snippet_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('min_rating', models.IntegerField()),
                ('directors', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
