# Generated by Django 5.1.1 on 2024-10-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0003_movies_delete_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
