# Generated by Django 5.1.1 on 2024-10-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0004_movies_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='director',
        ),
    ]
