# Generated by Django 5.1.1 on 2024-10-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0005_remove_movies_director'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='movies',
        ),
    ]
