# Generated by Django 5.1.1 on 2024-10-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0006_alter_movies_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='directors',
            new_name='director',
        ),
    ]
